name: 'PR Auto Describe'
description: 'Automatically generate descriptions for pull requests using OpenAI'
branding:
  icon: 'git-pull-request'
  color: 'blue'

inputs:
  github-token:
    description: 'GitHub token for API access'
    required: true
  openai-api-key:
    description: 'OpenAI API key for fetching AI suggestions'
    required: true
  openai-model:
    description: 'The OpenAI model to use'
    default: 'gpt-3.5-turbo'
    required: false
  github-api-base-url:
    description: 'GitHub API Base URL'
    default: 'https://api.github.com'
    required: false

runs:
  using: 'docker'
  image: 'Dockerfile'